# Generated by Django 5.2.3 on 2025-06-16 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URLAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL analizada')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de análisis')),
                ('heur_score', models.IntegerField(blank=True, null=True, verbose_name='Puntuación heurística')),
                ('heur_flags', models.TextField(blank=True, null=True, verbose_name='Indicadores heurísticos detectados')),
                ('vt_malicious', models.IntegerField(blank=True, null=True, verbose_name='Detecciones VT (maliciosas)')),
                ('vt_harmless', models.IntegerField(blank=True, null=True, verbose_name='Detecciones VT (benignas)')),
                ('ml_prediction', models.CharField(blank=True, max_length=20, null=True, verbose_name='Predicción ML')),
                ('ml_probability', models.FloatField(blank=True, null=True, verbose_name='Probabilidad ML')),
                ('verdict', models.CharField(blank=True, max_length=50, null=True, verbose_name='Veredicto global')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
