# Generated by Django 5.2.3 on 2025-06-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlanalysis',
            name='final_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Puntuación combinada final'),
        ),
    ]
